### DISCUSSION TITLE
Develop discussion

### DISCUSSION THREAD

**Discussion by crazymikefra** [crazymikefra/HA_RFPlayer#1] [Q&A]
This discussion is made to share develop bugs and solutions.

It is also possible to share new ideas

**Comment by Doubledom45** [comment]
Ok cela surement plus simple sur la discussion.
@+Dom
**### PS**: je modifierais un peu l'addon pour seulement avoir des choses un peu plus verbeux (provisoirement) dans les logs

**Comment by Doubledom45** [comment]
https://github.com/crazymikefra/HA_RFPlayerNext/issues/1#issuecomment-1445403393

Ok dis moi si c'est bon chez toi avec ton Push !
Il faut que fasse bascule des versions sur mon Odroid 

PS : ça tourne mieux effectivement, il y a encore du décodage à faire ! AC EDISIO JAMMING
Dommage de ne pas avoir garder le nom en entier ! sur les entités ...

**Comment by crazymikefra** [comment]
Je viens de refaire un push avec tes traces. L'OWL devrait passer désormais.

Pour les noms sur les entités, tu parles du suffixe sur 3 lettres ?
Si oui, oui ça me plait pas trop aussi.
Sur la version Next, j'aimerais justement créer un Device par ID avec des entités affiliées.
Cela sera plus lisible.

**Comment by crazymikefra** [comment]
Nouveau Push.
J'avais mal cablé mes "OR" ;-)

**Comment by Doubledom45** [comment]
`Sur la version Next, j'aimerais justement créer un Device par ID avec des entités affiliées.
Cela sera plus lisible.`
C'est ce que je voulais essayé, avoir une entité appareil et les sous entités des catégories des types..
Pour Edisio tu dois avoir ce qu'il te faut dans le log, ainsi que le JAMMING (lui est remis à 1 au boot donc faut le forcé à 0 [pour l'instant je faisais automation])

**Comment by crazymikefra** [comment]
Je viens de refaire une passe sur tes commentaires :
- Pour Edisio : Vu que je viens d'ajouter l'Infotype 15, ca devrait fonctionner
- Pour le Jamming : Il est bien traité mais il est vrai que je ne le remonte ptet pas à l'entité Jamming déjà présente
- Pour AC : Je ne trouve pas trace de ce protocole dans la doc. C'est bien un protocole ou une fonctionnalité ?

**Reply by Doubledom45** [reply]
`Pour AC : Je ne trouve pas trace de ce protocole dans la doc. C'est bien un protocole ou une fonctionnalité ?`
Il est vrai que fait partie de CHACON DIO les versions en 433

Le Jamming c'était le bord.. à implémenté de toute façon. Je vais voir si je peux te le modifier en préparation.

Un truc il faut que tu ajoutes la possibilité de mettre "" dans service yaml et EDISIOFRAME. [sinon on passe en mode yaml modifié dans développement]
 ```       
      selector:
        select:
          options:
              - ""
              - "X10"
              - "VISONIC"
              - "BLYSS"
              - "CHACON"
              - "OREGON"
              - "DOMIA"
              - "OWL"
              - "X2D"
              - "RTS"
              - "KD101"
              - "PARROT"
              - "TIC"
              - "FS20"
              - "JAMMING"
              - "EDISIO"
              - "EDISIOFRAME"
          mode: dropdown
```
