### ISSUE TITLE
Simplification méthode d'envoie

### ISSUE THREAD

**Issue by Doubledom45** [crazymikefra/HA_RFPlayer#13]
Salut Michael.
Je pense plus simple de modifier la commande d'envoie, et d'enlever les tests ! sur les protocoles ( pseudo, c'est commande)
Modification services.yaml seulement la description !

```
    device_address:
      name: Device address
      description: ID x or pseudo-address X10.
      required: false
      example: A1
      selector:
        text:
    device_id:
      name: Device ID
      description: Name for HA ID entity.
      required: false
      example: Corridor light
      selector:
        text:
    automatic_add:
      name: Create entity
      description: Create associated switch entity
      required: true
      default: false
      selector:
        boolean:
    entity_type:
      name: Entity type
      description: Type of entity created
      required: false
      default: switch
      selector:
        select:
          options:
              - "cover"
              - "number"
              - "sensor"
              - "switch"
          mode: dropdown
```
Il reste a voir la liste dans protocol pour éliminer ce qui ne sert plus

Pour le rfpprotocol.py
```
    def send_command(
        self,
        protocol: str,
        command: str,
        device_address: str = None,
        device_id: str = None,
    ) -> None:
            self.send_raw_packet(f"ZIA++{command} {device_address} {protocol}") #ATTENTION AU FORMAT DE LA COMMANDE !

class CommandSerialization(PacketHandling):
    """Logic for ensuring asynchronous commands are sent in order."""
